### ISSUE TITLE
Provide examples of Web Components that have been ported to AOM

### ISSUE THREAD

**Issue by jessebeach** [A11yance/react-aom-renderer#1]

**Comment by robdodson** [comment]
These are from our [howto-components project](https://github.com/GoogleChromeLabs/howto-components). I converted a checkbox and a tabs component over to AOM.

[Checkbox](https://github.com/GoogleChromeLabs/howto-components/blob/aom/elements/howto-checkbox/howto-checkbox.js)
[Tabs](https://github.com/GoogleChromeLabs/howto-components/blob/aom/elements/howto-tabs/howto-tabs.js)

One of the points of contention was whether ARIA or AOM should "win" if both are applied to an element. What's being discussed right now is the idea that AOM would win over ARIA if both were applied to an element. However, if an element has a ShadowRoot, then the element author could apply AOM directly to the Shadow Root to setup default semantics. If someone were to then use ARIA on the host, ARIA would win. If they were to apply ARIA and AOM to the host, then the AOM on the host would win.
