### ISSUE TITLE
Scaffold a minimally viable React Renderer setup

### ISSUE THREAD

**Issue by jessebeach** [A11yance/react-aom-renderer#2]
Follow the instructions laid out there: https://github.com/nitin42/Making-a-custom-React-renderer

Pull in the NPM packages necessary to get this to run.

Success criteria. The following outputs a `div` from the renderer.

```
import React from ‘react’;

const HelloWorld = ({name}) => (
 <div>{`Hi ${name}`}</div>
);

export default HelloWorld;
```

**Comment by AlmeroSteyn** [comment]
Going to try and see if I can get my head around this in the coming days. If anyone else gets it working quicker, that is great too 👍

**Comment by jessebeach** [comment]
@AlmeroSteyn Feel free to start a branch and push it.

**Comment by AlmeroSteyn** [comment]
Hey everyone, this is still very much on my radar to try and do. Just got snowed under with work and preparing a talk. Just so you know :-)

**Comment by jessebeach** [comment]
@AlmeroSteyn same same :)

**Comment by AlmeroSteyn** [comment]
Hey everyone, I had a look at this a couple of times and whereas the the instructions really helps, you will still need to dive deeper into the reconciler to properly understand what is at work here. With my current workload I am simply not getting the time needed to give this the attention it deserves at this stage :-( 

I have also been wondering if work done now will remain valid once async rendering lands? Anyone have a feel for this?
